# Generated by Django 4.1.2 on 2022-10-07 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadcolor',
            options={'verbose_name_plural': 'Thread Colors'},
        ),
        migrations.AlterModelOptions(
            name='userthread',
            options={'verbose_name_plural': 'User Threads'},
        ),
    ]
