# Generated by Django 4.1.2 on 2022-10-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_threadcolor_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadcolor',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.brand'),
        ),
    ]
