# Generated by Django 4.1.2 on 2022-10-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_threadcolor_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='threadcolor',
            constraint=models.UniqueConstraint(fields=('brand', 'brand_number', 'name'), name='unique_brand_color'),
        ),
        migrations.AddConstraint(
            model_name='userthread',
            constraint=models.UniqueConstraint(fields=('thread_data', 'owner',), name='unique_user_thread'),
        ),
    ]
