# Generated by Django 4.1.2 on 2023-01-11 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userthread_skeins_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthread',
            name='skeins_owned',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)]),
        ),
    ]
