# Generated by Django 4.1.1 on 2022-09-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadcolor',
            name='brand_number',
            field=models.CharField(max_length=10),
        ),
    ]
