# Generated by Django 4.1.1 on 2022-09-08 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_alter_threadcolor_brand_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skeins_owned', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.threadcolor')),
            ],
        ),
    ]
